#!/bin/bash -efu
#
# aacgain15 - normalize audio volume to the average of ReplayGain 1.0 and 2.0
#
# Written by Alexey Tourbin.
# This file is distributed as Public Domain.

av0=$(readlink -ev "$0")
av0dir=$(dirname "$av0")

. $av0dir/calc.sh
. $av0dir/dualmono.sh

tmpdir=${TMPDIR:-/tmp}
dry_run=

AACGain15()
{
	local ff_decode_pre=
	if [[ $1 = *.[Mm][Pp]3 ]]; then
		ff_decode_pre='-acodec mp3float'
	fi
	ffmpeg $ff_decode_pre -i "$1" -vn -af replaygain,ebur128=framelog=verbose \
		-f null - >$tmpdir/gain$$.log 2>&1 || { grep -i error $tmpdir/gain$$.log; false; }
	local vars
	vars=$($av0dir/aacgain15pp <$tmpdir/gain$$.log)
	local $vars
	if [ ${g0ch:?} = 1 ]; then
		DualMono rg1
		DualMono eb1
	fi
	vars=$(perl -e 'use v5.12;
		my $db1 = shift;
		my $db2 = shift;
		my $peak = shift;
		my $db = ($db1 + $db2) / 2;
		use POSIX qw(floor);
		my $igain = floor 0.5 + $db / (5 * log(2) / log(10));
		my $igain2db = $igain * (5 * log(2) / log(10));
		my $igaink = $igain;
		my $igaink2db = $igain2db;
		while ($peak + $igaink2db > 0.001) {
			$igaink--;
			$igaink2db = $igaink * (5 * log(2) / log(10));
		}
		my $dbleft  = 0 + sprintf "%.2f", $db - $igain2db;
		my $dbleftk = 0 + sprintf "%.2f", $db - $igaink2db;
		$db = 0 + sprintf "%.2f", $db;
		say "g1db=$db";
		say "g1igain=$igain";
		say "g1igaink=$igaink";
		say "g1dbleft=$dbleft";
		say "g1dbleftk=$dbleftk";
		' -- ${rg1gain:?} ${eb1gain:?} ${rg1peak:?})
	local $vars
	if [ -n "$dry_run" ]; then
		echo rg1gain=$rg1gain eb1gain=$eb1gain g1db=$g1db \
		     eb1range=$eb1range eb1rlow=$eb1rlow rg1peak=$rg1peak
		local snow='\033[1;37m' red='\033[1;31m' nc='\033[0m'
		[ -t 1 ] || snow= red= nc=
		[ ${g1igain:?} = ${g1igaink:?} ] && red=
		# Can go up, even with clipping restrictions?
		if [ $g1igaink -gt 0 ]; then
		    printf "${red}g1igain=$g1igain$nc ${snow}g1igaink=$g1igaink$nc"
		# Or do they generally suggest we go down?
		# (perhaps not as much as with clipping restrictions)
		elif [ $g1igain -lt 0 ]; then
		    printf "${snow}g1igain=$g1igain$nc ${red}g1igaink=$g1igaink$nc"
		# Otherwise, no good plan (or nothing to do).
		else
		    printf "${red}g1igain=$g1igain g1igaink=$g1igaink$nc"
		fi
		echo '' g1dbleft=$g1dbleft g1dbleftk=$g1dbleftk
	else
		if [ $g1igaink -gt 0 ]; then
		    echo >&2 "${0##*/}: applying gain $g1igaink to $1"
		    aacgain -q -g $g1igaink -s s "$1" >&2
		elif [ $g1igain -lt 0 ]; then
		    echo >&2 "${0##*/}: applying gain $g1igain to $1"
		    aacgain -q -g $g1igain -s s "$1" >&2
		fi
	fi
	rm $tmpdir/gain$$.log
}

if [ "${1-}" = "-n" ]; then
	dry_run=1
	shift
fi

for f; do
	AACGain15 "$f"
done
