#!/bin/bash -efu

tmpdir=${TMPDIR:-/tmp}

AACGain15()
{
	local db1 db2 range vars
	aacgain "$1" | tee $tmpdir/gain1.log >&2
	db1=$(perl -lne 's/.*\s+dB change:\s+// and print 0+$_ and exit' $tmpdir/gain1.log)
	bs1770gain --replaygain --range "$1" | tee $tmpdir/gain2.log >&2
	db2=$(perl -lne 's/.*integrated:.*\/\s+// and print 0+$_ and exit' $tmpdir/gain2.log)
	range=$(perl -lne 's/.*range:\s+// and print 0+$_ and exit' $tmpdir/gain2.log)
	vars=$(perl -e '
		use v5.12;
		use POSIX qw(floor);
		my $db1 = shift;
		my $db2 = shift;
		my $db = ($db1 + $db2) / 2;
		say "db1=$db1 db2=$db2 db=$db";
		my $gain = $db / (5 * log(2) / log(10));
		my $igain = floor(0.5 + $gain);
		my $igain2db = $igain * (5 * log(2) / log(10));
		my $dbleft = 0 + sprintf "%.2f", $db - $igain2db;
		say "igain=$igain dbleft=$dbleft";
		' -- ${db1:?} ${db2:?} )
	local $vars
	echo $vars range=${range:?}
	[ ${igain:?} = 0 ] ||
	aacgain -g "$igain" "$1" >&2
}

for f; do
	AACGain15 "$f"
done
