#!/bin/bash -efu
#
# ismono - detect if the input signal is mono
#
# Written by Alexey Tourbin.
# This file is distributed as Public Domain.

av0=$(readlink -ev "$0")
av0dir=$(dirname "$av0")

tmpdir=${TMPDIR:-/tmp}

. $av0dir/calc.sh
. $av0dir/dualmono.sh

# seek and duration support
. $av0dir/ffseek.sh

# predefined album gain
gain=

IsMono()
{
	ffseek
	. $av0dir/mono.sh
	echo c0db=$c0db g1db=$g1db q999=$q999 q99=$q99 ismono=$ismono
	rm $tmpdir/gain$$.log
}

argv=$(getopt -n "${0##*/}" -o t:g: -al ss:,to:,gain: -- "$@")
eval set -- "$argv"
while :; do
	case "$1" in
		--ss) ff_ss=${2:?}; shift 2 ;;
		--to) ff_to=${2:?}; shift 2 ;;
		-t) ff_t=${2:?}; shift 2 ;;
		-g|--gain) gain=${2:?}; shift 2 ;;
		--) shift; break ;;
		*) echo >&2 "unrecognized option: $1"; false ;;
	esac
done

for f; do
	IsMono "$f"
done
