#!/bin/bash -efux
#
# transcode - transcode radio programs for portable use
#
# Written by Alexey Tourbin.
# This file is distributed as Public Domain.

tmpdir=${TMPDIR:-/tmp}

av0=$(readlink -ev "$0")
av0dir=$(dirname "$av0")

# autodetect mono
mono=

# use deafult aac priming
priming=

# use dynamic range compression when appropriate
no_drc=

# compress towards this dynamic range
drc_range=10dB

# seek and duration support
. $av0dir/ffseek.sh

# quality control
VBR= TVBR=

Transcode()
{
	ffseek

	local ff_decode_pre=
	if [[ $1 = *.[Mm][Pp]3 ]]; then
		ff_decode_pre='-acodec mp3float'
	fi

	ffmpeg $ff_decode_pre ${ff_ss:+-ss $ff_ss} -i "$1" ${ff_t:+-t $ff_t} -vn \
		-af replaygain,ebur128=framelog=verbose,pan='mono|c0=0.5*c0+-0.5*c1',replaygain=percent=99 \
		-f null - >$tmpdir/gain$$.log 2>&1 || { grep -i error $tmpdir/gain$$.log; false; }

	local vars
	vars=$($av0dir/aacgain15pp <$tmpdir/gain$$.log)
	local $vars

	local vbr=4 tvbr=82
	[ ${g0brate:?} -lt 180 ] || vbr=3 tvbr=91

	local codec=${g0codec:?}
	local format=${g0format:?}

	if [ $codec = mp2 ]; then
		ff_decode_pre='-acodec mp2float'
	fi
	if [ $codec = mp3 ]; then
		ff_decode_pre='-acodec mp3float'
	fi

	# -af chain
	local AF=

	if [ ${g0ch:?} -gt 2 ]; then
		AF=${AF:+$AF,}aresample='ocl=stereo'
	fi

	case $mono in
		no) mono= ;;
		'') mono=$(perl -e "print 1 if ${g2db1:?} - ${g1db:?} > 20") ;;
	esac

	if [ -n "$mono" ]; then
		AF=${AF:+$AF,}pan='mono|c0=0.5*c0+0.5*c1'
	fi

	local drc=
	if [ -z "$no_drc" ] && [ ${g1range%.*} -gt ${drc_range%dB} ]; then
		vars=$(perl -le '
			use v5.12;
			my $range  = shift;
			my $dbleft = shift;
			my $rlow   = shift;
			my $target = shift;
			my $ratio  = 0 + sprintf "%.2f", $range / ($target + ($range - $target) / 3);
			my $thresh = 0 + sprintf "%.0f", (-15 - $range - $dbleft + $rlow) / 2;
			my $knee   = 0 + sprintf "%.0f", 2 * $range;
			say "ratio=$ratio thresh=$thresh knee=$knee";
			' -- $g1range $g1db $g1rlow $drc_range)
		local $vars
		drc="asplit[i1][i2];[i1]qadrc=$thresh:$ratio:$knee[o1];[i2]mydrc=$(($thresh-2)):$ratio:$knee[o2];[o1][o2]amix"
		AF=${AF:+$AF,}$drc

		ffmpeg $ff_decode_pre ${ff_ss:+-ss $ff_ss} -i "$1" ${ff_t:+-t $ff_t} -vn \
			-af "$AF",replaygain,ebur128=framelog=verbose \
			-f null - >$tmpdir/gain$$.log 2>&1 || { grep -i error $tmpdir/gain$$.log; false; }

		vars=$($av0dir/aacgain15pp <$tmpdir/gain$$.log)
		local $vars
	fi

	if [ ${g1db:?} != 0 ]; then
		AF=${AF:+$AF,}volume=${g1db}dB
	fi

	local limiter
	limiter=$(perl -le "print 1 if ${g1peak:?} + $g1db > -0.071")
	if [ -n "$limiter" ]; then
		AF=${AF:+$AF,}qalimiter
	fi

	if [[ $2 = *.[Mm][Pp]3 ]]; then
		ffmpeg $ff_decode_pre -i "$1" ${ff_ss:+-ss $ff_ss} ${ff_t:+-t $ff_t} -vn \
			${AF:+-af "$AF"} -aq ${VBR:-$vbr} -y "$2"
	else
		adts=
		[[ $2 != *.[Aa][Aa][Cc] ]] || adts='--adts'
		priming=${priming:+--num-priming=$priming}
		set -o pipefail
		ffmpeg $ff_decode_pre ${ff_ss:+-ss $ff_ss} -i "$1" ${ff_t:+-t $ff_t} -vn \
			${AF:+-af "$AF"} -acodec pcm_f32le -f wav - |
		qaac -o "$2" $priming $adts --tvbr=${TVBR:-$tvbr} -
		set +o pipefail
	fi
}

argv=$(getopt -n "${0##*/}" -o t:V: -al mono,stereo,no-drc,drc-range:,priming:,ss:,to:,tvbr: -- "$@")
eval set -- "$argv"
while :; do
	case "$1" in
		--mono) mono=yes; shift ;;
		--stereo) mono=no; shift ;;
		--no-drc) no_drc=1; shift ;;
		--drc-range) drc_range=${2:?}; shift 2;;
		--priming) priming=${2:?}; shift 2 ;;
		--ss) ff_ss=${2:?}; shift 2 ;;
		--to) ff_to=${2:?}; shift 2 ;;
		-t) ff_t=${2:?}; shift 2 ;;
		-V) VBR=${2:?}; shift 2 ;;
		--tvbr) TVBR=${2:?}; shift 2 ;;
		--) shift; break ;;
		*) echo >&2 "unrecognized option: $1"; false ;;
	esac
done

Transcode "$1" "${2:-${1%.*}.mp3}"
