#!/bin/bash -efux

tmpdir=${TMPDIR:-/tmp}

av0=$(readlink -ev "$0")
av0dir=$(dirname "$av0")

PrintIfMono()
{
	ffmpeg -i "$1" -vn -af pan=mono:"c0=0.5*c0+-0.5*c1",volumedetect -f null -y /dev/null >$tmpdir/ismono 2>&1
	avg=$(grep -ao 'mean_volume: .*' $tmpdir/ismono); avg=$(set $avg && echo ${2%.*})
	max=$(grep -ao  'max_volume: .*' $tmpdir/ismono); max=$(set $max && echo ${2%.*})
	q999=$(perl -lne 'print -$1 if /histogram_(\d+)db/' $tmpdir/ismono |tail -1)
	if [ ${q999:?} -le -40 ]; then
		echo 1
	fi
}

Transcode()
{
	vbr=4
	bitrate=$(avconv -i "$1" 2>&1 |
		  perl -ne '/^\s+Stream .* Audio: aac, .* ([1-9]\d\d?) kb/ and print $1 and exit')
	[ ${bitrate:?} -lt 200 ] || vbr=3

	gvars=$($av0dir/aacgain15 "$1")
	local $gvars
	local gain=${dbleft:?}

	mono=$(PrintIfMono "$1")
	echo '1 1' >$tmpdir/mono.matrix
	mono=${mono:+--matrix-file $tmpdir/mono.matrix}

	local drc=
	if [ "${range%.*}" -ge 10 ]; then
		vars=$(perl -le '
			use v5.12;
			my $range = shift;
			my $dbleft = shift;
			my $ratio = 0 + sprintf "%.2f", 1 + ($range - 9.8) / 20;
			my $thresh = 0 + sprintf "%.1f", -30 - $dbleft - ($range - 10) / 2;
			my $knee = 0 + sprintf "%.1f", 25 + 1.5 * $range;
			say "ratio=$ratio thresh=$thresh knee=$knee";
			' -- $range $dbleft)
		local $vars
		drc="--drc $thresh:$ratio:$knee:20:800"

		local fast='-V5 -q9 --noreplaygain --nohist'
		[ -n "$mono" ] || fast="$fast -ms"

		qaac --silent --decode $mono $drc -o - "$1" |
		lame $fast /dev/stdin $tmpdir/drc.mp3

		gvars=$($av0dir/aacgain15 $tmpdir/drc.mp3)
		local $gvars
		gain=${db:?}
	fi

	[ "$gain" != 0 ] || gain=
	gain=${gain:+--gain $gain}

	qaac --silent --decode $mono $drc $gain --limiter -o - "$1" |
	lame -V$vbr /dev/stdin "$2"
}

Transcode "$1" "${2:-${1%.*}.mp3}"
